version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: install ansible
          command: |
            sudo apt update
            sudo apt install ansible
            sudo apt-get install -y ansible-lint
      - run:
          name: verify ansible is installed
          command: ansible --version
      - run:
          name: install molecule
          command: pip3 install molecule molecule-docker
      - run:
          name: verify molecule is installed
          command: molecule --version
      - run:
          name: list dirs
          command: |
            pwd
            ls -R
      - run:
          name: create molecule instance
          command: molecule create
          working_directory: ./ansible_role_redis
      - run:
          name: verify molecule instance
          command: molecule list
          working_directory: ./ansible_role_redis
      - run:
          name: test our role with molecule
          command: molecule converge
          working_directory: ./ansible_role_redis
      - run:
          name: destroy molecule instance
          command: molecule destroy
          working_directory: ./ansible_role_redis
