version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: install ansible
          command: |
            sudo apt update
            sudo apt install ansible
            sudo apt-get install -y ansible-lint
      - run:
          name: verify ansible is installed
          command: ansible --version
      - run:
          name: install molecule
          command: pip3 install molecule docker
      - run:
          name: verify molecule is installed
          command: molecule --version
      - run:
          name: list dirs
          command: |
            pwd
            ls -R
      - run:
          name: test docker works
          command: docker run hello-world
          working_directory: ./ansible_role_redis
